"""A custom head as a folder on disk.

Deliberately plain: a folder with a mesh, optionally a texture, optionally a
small manifest. No archive format, no database. A head someone can inspect,
edit and hand to somebody else without this tool is worth more than a tidy
container.

    my_head/
      head.obj          required - the geometry
      head.tga          optional - a texture; its filename becomes the resref
      head.json         optional - metadata and fitting hints

`head.json` carries only what cannot be read off the mesh:

    {
      "name":      "Tripo Alien",       display name
      "author":    "someone",
      "notes":     "generated by Tripo, retopologised",
      "target":    "head",              which node this is meant for
      "facing":    "+y",                which way the mesh looks, if not +y
      "scale":     1.15,                multiply the fitted size by this
      "anchor":    "chin"               "chin" or "centre"
    }

Everything in it is a hint. Nothing in it is trusted over what the geometry
actually says, and a pack with no manifest at all is still valid.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

MESH_NAMES = ("head.obj", "mesh.obj")
TEXTURE_SUFFIXES = (".tga", ".tpc")
MANIFEST_NAME = "head.json"

VALID_FACING = ("+y", "-y", "+x", "-x")
VALID_ANCHOR = ("chin", "centre", "center")
VALID_UP = ("z", "y")


@dataclass
class HeadPack:
    root: Path
    mesh_path: Path | None = None
    texture_path: Path | None = None
    manifest: dict = field(default_factory=dict)
    problems: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return self.mesh_path is not None and not self.problems

    @property
    def name(self) -> str:
        return str(self.manifest.get("name") or self.root.name)

    @property
    def target(self) -> str:
        return str(self.manifest.get("target") or "head")

    @property
    def scale(self) -> float:
        try:
            return float(self.manifest.get("scale", 1.0))
        except (TypeError, ValueError):
            return 1.0

    @property
    def anchor(self) -> str:
        return str(self.manifest.get("anchor") or "chin").lower()

    @property
    def facing(self) -> str:
        return str(self.manifest.get("facing") or "+y").lower()

    @property
    def up(self) -> str:
        """Which axis the mesh calls up. KOTOR is Z-up; many tools export Y-up."""
        return str(self.manifest.get("up") or "z").lower()

    @property
    def texture_resref(self) -> str | None:
        return self.texture_path.stem if self.texture_path else None


def load(folder: str | Path) -> HeadPack:
    """Read a head pack. Never raises - problems are collected and reported."""
    root = Path(folder)
    pack = HeadPack(root=root)

    if not root.is_dir():
        pack.problems.append(f"{root} is not a folder")
        return pack

    for candidate in MESH_NAMES:
        if (root / candidate).is_file():
            pack.mesh_path = root / candidate
            break
    else:
        loose = sorted(root.glob("*.obj"))
        if len(loose) == 1:
            pack.mesh_path = loose[0]
        elif loose:
            pack.problems.append(
                f"several .obj files and none named head.obj: "
                f"{', '.join(p.name for p in loose)}"
            )
        else:
            pack.problems.append("no .obj mesh in the folder")

    textures = [p for p in sorted(root.iterdir())
                if p.is_file() and p.suffix.lower() in TEXTURE_SUFFIXES]
    if len(textures) == 1:
        pack.texture_path = textures[0]
    elif textures:
        pack.problems.append(
            f"several textures and no way to choose: "
            f"{', '.join(p.name for p in textures)}"
        )

    manifest = root / MANIFEST_NAME
    if manifest.is_file():
        try:
            data = json.loads(manifest.read_text(encoding="utf-8"))
            if not isinstance(data, dict):
                pack.problems.append(f"{MANIFEST_NAME} is not a JSON object")
            else:
                pack.manifest = data
        except ValueError as exc:
            pack.problems.append(f"{MANIFEST_NAME} is not valid JSON: {exc}")

    # Hints are checked, but a bad hint is never fatal - the geometry decides.
    if pack.manifest:
        if pack.facing not in VALID_FACING:
            pack.problems.append(
                f"facing {pack.facing!r} is not one of {', '.join(VALID_FACING)}"
            )
        if pack.anchor not in VALID_ANCHOR:
            pack.problems.append(
                f"anchor {pack.anchor!r} is not one of {', '.join(VALID_ANCHOR)}"
            )
        if pack.up not in VALID_UP:
            pack.problems.append(
                f"up {pack.up!r} is not one of {', '.join(VALID_UP)}"
            )
        if not 0.1 <= pack.scale <= 10.0:
            pack.problems.append(f"scale {pack.scale} is outside a sane 0.1 to 10")
    return pack


def write_template(folder: str | Path, name: str = "My Head") -> Path:
    """Write a manifest a person can fill in, with every field explained."""
    root = Path(folder)
    root.mkdir(parents=True, exist_ok=True)
    path = root / MANIFEST_NAME
    path.write_text(
        json.dumps(
            {
                "name": name,
                "author": "",
                "notes": "",
                "target": "head",
                "facing": "+y",
                "up": "z",
                "scale": 1.0,
                "anchor": "chin",
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    return path
